staticDir = ["static"]
baseurl = "http://www.cryptocoinmarketwatch.com/"
languageCode = "en-us"
copyright = "(c) 2017 Crypto Coin Market Watch"
canonifyurls = true
paginate = 3
theme = "hugo-gentoo-theme"
googleAnalytics = "Yout Google Analytics ID"
title = "Crypto Coin Market Watch - Everything Crypto"

[params]
  description = "Everything Crypto"
  author = "Johnny Coin"

[taxonomies]
  category = "categories"
  tag = "tags"


[[menu.global]]
    

[[menu.footer]]


