staticDir = ["static"]
baseurl = "http://www.cryptocoinmarketwatch.com/"
languageCode = "en-us"
title = "Crypto Coin Market Watch"
copyright = "(c) 2017 Crypto Coin Market Watch"
canonifyurls = true
paginate = 3
googleAnalytics = "UA-110928648-1"
theme = "hugo-gentoo-theme"

[params]
  description = "Everything Crypto"
  author = "Johnny Coin"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.global]]
    name = "Categories"
    url = "/categories/"

[[menu.global]]
    name = "Tags"
    url = "/tags/"

[[menu.footer]]
    name = "About"
    url = "/page/about/"
    
[sitemap]
  changefreq = "monthly"
  priority = 0.5
filename = "sitemap.xml"
